### ISSUE TITLE
Fix warnings on base template

### ISSUE THREAD

**Issue by carletex** [BuidlGuidl/event-wallet#39]
`yarn next:lint` throw a bunch of warnings (mostly useEffect missing deps):

![image](https://github.com/BuidlGuidl/event-wallet/assets/2486142/16961758-2a2e-403f-8641-18afa030d2ab)

Let's fix them on the base template! While building we also removed `--max-warnings=0` on the GH Action `lint.yaml`. Should we add it back?

**Comment by damianmarti** [comment]
@carletex Yes, I think we should add --max-warnings=0 again. Adding it in the same PR.
