### ISSUE TITLE
Make the credit balance box less wide

### ISSUE THREAD

**Issue by damianmarti** [BuidlGuidl/event-wallet#66]
The credit balance box is too wide. We only show 4 decimals here, so the number shouldn't be so big. Maybe we can use a smaller width and center it.

![localhost_3000_ (28)](https://github.com/BuidlGuidl/event-wallet/assets/466652/2decd7cf-2b36-4a6b-9c43-bb6291565d32)

**Comment by damianmarti** [comment]
@ceeriil did you work on this?

**Comment by ceeriil** [comment]
Yeah I can remember doing this. I’ll check as soon as I can
