### ISSUE TITLE
Sell button looks as disabled

### ISSUE THREAD

**Issue by damianmarti** [BuidlGuidl/event-wallet#67]
The sell button is looking as always disabled:

![localhost_3000_ (29)](https://github.com/BuidlGuidl/event-wallet/assets/466652/c36527d3-4eda-4f4c-ab1d-86eb402e86a5)

It should look with a gray background only when the button is disabled. The buy button should have the same behavior.

The enabled sell button should look like this:

![www figma com_file_sdU2eoR4I4iTAgHj2FSKk4_game-wallet_type=design node-id=287-3628 mode=design t=MR3HtmKLCTixvVVO-0](https://github.com/BuidlGuidl/event-wallet/assets/466652/d9d93e73-423d-4087-bddd-eaa372219210)

**Comment by Ifechukwudaniel** [comment]
Am working  on this

**Comment by damianmarti** [comment]
@Ifechukwudaniel did you work on this?
