### ISSUE TITLE
Replace salt/credit emoji with CashIcon

### ISSUE THREAD

**Issue by damianmarti** [BuidlGuidl/event-wallet#68]
Replace the salt/credit emoji with the CashIcon everywhere.

![localhost_3000_ (30)](https://github.com/BuidlGuidl/event-wallet/assets/466652/010e0d41-16dc-4181-aa38-f6eb80213463)

**Comment by Ifechukwudaniel** [comment]
@ceeriil  said he will work on this

**Comment by damianmarti** [comment]
@ceeriil did you work on this?
