### ISSUE TITLE
Implement new design to dashboard page

### ISSUE THREAD

**Issue by damianmarti** [BuidlGuidl/event-wallet#72]
Dashboard page at /dashboard

Keep current chart styles.

![dashboard2](https://github.com/BuidlGuidl/event-wallet/assets/466652/4e63438b-7060-43e5-aa8e-7a1a4fbdd703)

**Comment by IbrahimIjai** [comment]
Can I contribute?

**Comment by IbrahimIjai** [comment]
Please can You assign this to me?

**Comment by IbrahimIjai** [comment]
Noted

**Comment by Ifechukwudaniel** [comment]
@IbrahimIjai  yeah try it

**Comment by damianmarti** [comment]
@IbrahimIjai did you work on this?

**Comment by IbrahimIjai** [comment]
> @IbrahimIjai did you work on this?

Yup I started, didn't didn't finish, I will finish up by tomorrow and push changes
